blueprint:
  name: IKEA BILRESA Matter (9-Button Mode) v2
  description: >
    "Corrects the logic for the IKEA BILRESA / SOMRIG style devices that expose 9 button entities.
    
    **How it works:**
    The device converts scroll actions into 'Virtual Button' presses.
    - **Group 1:** Btn 1 (Click), Btn 2 (Scroll Up), Btn 3 (Scroll Down)
    - **Group 2:** Btn 4 (Click), Btn 5 (Scroll Up), Btn 6 (Scroll Down)
    - **Group 3:** Btn 7 (Click), Btn 8 (Scroll Up), Btn 9 (Scroll Down)
    
    **Instructions:**
    1. Select the Matter Device.
    2. Map the actions below.
    3. Use the 'Smooth Dimmer' script for the scroll actions for best results."
  domain: automation
  input:
    matter_device_id:
      name: Matter Device
      description: Select the IKEA device (Not the entities, the device itself).
      selector:
        device:
          integration: matter
          multiple: false

    # --- GROUP 1 ---
    g1_label:
      name: "--- GROUP 1 (Default) ---"
      description: "Mappings for Endpoints 1, 2, 3"
      selector:
        label: {}

    action_g1_click:
      name: Click (Button 1)
      default: []
      selector:
        action: {}

    action_g1_scroll_up:
      name: Scroll Up / Right (Button 2)
      description: "Triggered when you rotate right in Group 1."
      default: []
      selector:
        action: {}

    action_g1_scroll_down:
      name: Scroll Down / Left (Button 3)
      description: "Triggered when you rotate left in Group 1."
      default: []
      selector:
        action: {}

    # --- GROUP 2 ---
    g2_label:
      name: "--- GROUP 2 (One Dot) ---"
      description: "Mappings for Endpoints 4, 5, 6"
      selector:
        label: {}

    action_g2_click:
      name: Click (Button 4)
      default: []
      selector:
        action: {}

    action_g2_scroll_up:
      name: Scroll Up / Right (Button 5)
      default: []
      selector:
        action: {}

    action_g2_scroll_down:
      name: Scroll Down / Left (Button 6)
      default: []
      selector:
        action: {}

    # --- GROUP 3 ---
    g3_label:
      name: "--- GROUP 3 (Two Dots) ---"
      description: "Mappings for Endpoints 7, 8, 9"
      selector:
        label: {}

    action_g3_click:
      name: Click (Button 7)
      default: []
      selector:
        action: {}

    action_g3_scroll_up:
      name: Scroll Up / Right (Button 8)
      default: []
      selector:
        action: {}

    action_g3_scroll_down:
      name: Scroll Down / Left (Button 9)
      default: []
      selector:
        action: {}

mode: queued
max: 10

trigger:
  - platform: event
    event_type: matter_event
    event_data:
      device_id: !input matter_device_id

variables:
  # Extract the Endpoint ID (1-9) which tells us which 'Virtual Button' was pressed
  endpoint_id: "{{ trigger.event.data.endpoint_id | int }}"
  
  # We removed the strict 'cluster_id' and 'command_id' checks.
  # If the endpoint is valid (1-9), we assume it's a valid action.
  
action:
  - choose:
      # --- GROUP 1 ---
      - conditions: "{{ endpoint_id == 1 }}"
        sequence: !input action_g1_click
      - conditions: "{{ endpoint_id == 2 }}"
        sequence: !input action_g1_scroll_up
      - conditions: "{{ endpoint_id == 3 }}"
        sequence: !input action_g1_scroll_down

      # --- GROUP 2 ---
      - conditions: "{{ endpoint_id == 4 }}"
        sequence: !input action_g2_click
      - conditions: "{{ endpoint_id == 5 }}"
        sequence: !input action_g2_scroll_up
      - conditions: "{{ endpoint_id == 6 }}"
        sequence: !input action_g2_scroll_down

      # --- GROUP 3 ---
      - conditions: "{{ endpoint_id == 7 }}"
        sequence: !input action_g3_click
      - conditions: "{{ endpoint_id == 8 }}"
        sequence: !input action_g3_scroll_up
      - conditions: "{{ endpoint_id == 9 }}"
        sequence: !input action_g3_scroll_down