blueprint:
  name: IKEA BILRESA Matter Scroll Wheel
  description: >
    "Advanced controller for the IKEA BILRESA Matter Scroll Wheel.
    
    **Features:**
    - **Click:** Recognized via Matter Generic Switch (Cluster 59).
    - **Scroll:** Recognized via Matter LevelControl (Cluster 8).
    - **Multi-Group Support:** Optionally link an Input Select helper to toggle between modes (e.g., Lights, Media, Blinds).
    
    **Instructions:**
    1. Select your IKEA Matter Device.
    2. (Optional) Create a Dropdown Helper (Input Select) with names like 'Group 1', 'Group 2' and select it below.
    3. Map your actions for each group."
    
  domain: automation
  input:
    matter_device_id:
      name: Matter Device
      description: Select the IKEA BILRESA device.
      selector:
        device:
          integration: matter
          multiple: false

    group_helper:
      name: Group Helper (Optional)
      description: >
        "An Input Select entity to track the current group/mode. 
        If left empty, only 'Group 1' actions will ever execute."
      default: {}
      selector:
        entity:
          domain: input_select
          multiple: false

    # ---------------- GROUP 1 ----------------
    g1_label:
      name: "--- GROUP 1 SETTINGS ---"
      description: "Default actions. (Active if Helper is empty or set to Group 1)"
      default: {}
      selector:
        label: {}

    action_click_g1:
      name: Single Click (Group 1)
      description: "Action for single press. (Recommended: 'Input Select: Select next' to switch groups)"
      default: []
      selector:
        action: {}

    action_scroll_up_g1:
      name: Scroll Up / Right (Group 1)
      description: "Action when rotating clockwise (e.g., Brightness Up)."
      default: []
      selector:
        action: {}

    action_scroll_down_g1:
      name: Scroll Down / Left (Group 1)
      description: "Action when rotating counter-clockwise (e.g., Brightness Down)."
      default: []
      selector:
        action: {}

    # ---------------- GROUP 2 ----------------
    g2_label:
      name: "--- GROUP 2 SETTINGS ---"
      description: "Active only if Helper is set to 'Group 2'"
      default: {}
      selector:
        label: {}

    action_click_g2:
      name: Single Click (Group 2)
      default: []
      selector:
        action: {}

    action_scroll_up_g2:
      name: Scroll Up / Right (Group 2)
      default: []
      selector:
        action: {}

    action_scroll_down_g2:
      name: Scroll Down / Left (Group 2)
      default: []
      selector:
        action: {}

    # ---------------- GROUP 3 ----------------
    g3_label:
      name: "--- GROUP 3 SETTINGS ---"
      description: "Active only if Helper is set to 'Group 3'"
      default: {}
      selector:
        label: {}

    action_click_g3:
      name: Single Click (Group 3)
      default: []
      selector:
        action: {}

    action_scroll_up_g3:
      name: Scroll Up / Right (Group 3)
      default: []
      selector:
        action: {}

    action_scroll_down_g3:
      name: Scroll Down / Left (Group 3)
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: matter_event
    event_data:
      event_source: !input matter_device_id

variables:
  # --- INPUTS ---
  helper_entity: !input group_helper
  
  # --- EVENT DATA ---
  cluster_id: "{{ trigger.event.data.cluster_id }}"
  command_id: "{{ trigger.event.data.command_id }}"
  args: "{{ trigger.event.data.args }}"
  
  # --- GROUP LOGIC ---
  current_group: >
    {% if helper_entity == {} %}
      Group 1
    {% else %}
      {{ states(helper_entity) }}
    {% endif %}

  # --- CLUSTER DECODING ---
  
  # 1. CLICK DETECTION (Generic Switch Cluster = 59 / 0x003B)
  # Based on your image: 'multi_press_1' usually maps to MultiPressComplete (Cmd 6) with count 1.
  # We also accept ShortRelease (Cmd 2) as a fallback for faster response if supported.
  is_click: >
    {{ 
      (cluster_id == 59 and command_id == 6 and (args.totalNumberOfPressesCounted | default(1) == 1))
      or
      (cluster_id == 59 and command_id == 2)
    }}

  # 2. SCROLL DETECTION (LevelControl Cluster = 8 / 0x0008)
  # Command 2 = Step. 
  # args.stepMode (or args[0]): 0 = Up, 1 = Down.
  # Note: Some firmware versions use Move (Cmd 5), but Step is standard for wheels.
  is_scroll_up: >
    {{ 
      cluster_id == 8 and 
      (command_id == 2 or command_id == 5) and 
      (args.stepMode | default(args[0]) | int == 0)
    }}
    
  is_scroll_down: >
    {{ 
      cluster_id == 8 and 
      (command_id == 2 or command_id == 5) and 
      (args.stepMode | default(args[0]) | int == 1)
    }}

action:
  - choose:
      # --- GROUP 1 ACTIONS ---
      - conditions:
          - "{{ current_group == 'Group 1' }}"
        sequence:
          - choose:
              - conditions: "{{ is_click }}"
                sequence: !input action_click_g1
              - conditions: "{{ is_scroll_up }}"
                sequence: !input action_scroll_up_g1
              - conditions: "{{ is_scroll_down }}"
                sequence: !input action_scroll_down_g1

      # --- GROUP 2 ACTIONS ---
      - conditions:
          - "{{ current_group == 'Group 2' }}"
        sequence:
          - choose:
              - conditions: "{{ is_click }}"
                sequence: !input action_click_g2
              - conditions: "{{ is_scroll_up }}"
                sequence: !input action_scroll_up_g2
              - conditions: "{{ is_scroll_down }}"
                sequence: !input action_scroll_down_g2

      # --- GROUP 3 ACTIONS ---
      - conditions:
          - "{{ current_group == 'Group 3' }}"
        sequence:
          - choose:
              - conditions: "{{ is_click }}"
                sequence: !input action_click_g3
              - conditions: "{{ is_scroll_up }}"
                sequence: !input action_scroll_up_g3
              - conditions: "{{ is_scroll_down }}"
                sequence: !input action_scroll_down_g3