blueprint:
  name: IKEA Bilresa Scroll Wheel Remote
  description: Control lights, media, and more with the IKEA Bilresa scroll wheel remote. Supports Matter, ZHA, and Zigbee2MQTT.
  domain: automation
  input:
    # ========================================
    # DEVICE SELECTION
    # ========================================
    remote_device:
      name: ðŸŽ›ï¸ Remote Device
      description: Select your Bilresa scroll wheel remote
      selector:
        device:
          integration: matter
          manufacturer: IKEA of Sweden
    
    # ========================================
    # BUTTON ACTIONS
    # ========================================
    single_press_action:
      name: "â­• Single Press"
      description: Action when button is pressed once
      default: []
      selector:
        action: {}
    
    double_press_action:
      name: "â­•â­• Double Press"
      description: Action when button is pressed twice quickly
      default: []
      selector:
        action: {}
    
    long_press_action:
      name: "â­• Long Press"
      description: Action when button is held down
      default: []
      selector:
        action: {}
    
    # ========================================
    # SCROLL WHEEL - BASIC MODE
    # ========================================
    scroll_up_action:
      name: "ðŸ”¼ Scroll Up"
      description: Action when scrolling up/right
      default: []
      selector:
        action: {}
    
    scroll_down_action:
      name: "ðŸ”½ Scroll Down"
      description: Action when scrolling down/left
      default: []
      selector:
        action: {}
    
    # ========================================
    # SCROLL WHEEL - SMOOTH DIMMING
    # ========================================
    smooth_dimming_entity:
      name: "ðŸ’¡ Smooth Dimming Light"
      description: "Light to control with smooth dimming (leave empty to disable)"
      default: ""
      selector:
        entity:
          domain: light
    
    smooth_step_size:
      name: "ðŸ“Š Dimming Step Size"
      description: "How much to change brightness per scroll notch (percentage)"
      default: 4
      selector:
        number:
          min: 1
          max: 20
          step: 1
          unit_of_measurement: "%"
          mode: slider
    
    # ========================================
    # GROUP 1 - SCROLL ACTIONS
    # ========================================
    group1_action:
      name: "ðŸ”µ Group 1 - Scroll Action"
      description: "Action when scrolling while Group 1 is active"
      default: []
      selector:
        action: {}
    
    # ========================================
    # GROUP 2 - SCROLL ACTIONS
    # ========================================
    group2_action:
      name: "ðŸŸ¢ Group 2 - Scroll Action"
      description: "Action when scrolling while Group 2 is active"
      default: []
      selector:
        action: {}
    
    # ========================================
    # GROUP 3 - SCROLL ACTIONS
    # ========================================
    group3_action:
      name: "ðŸŸ¡ Group 3 - Scroll Action"
      description: "Action when scrolling while Group 3 is active"
      default: []
      selector:
        action: {}

# ========================================
# TRIGGERS
# ========================================
trigger:
  - platform: event
    event_type: matter_event
    event_data:
      device_id: !input remote_device
  
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device
  
  - platform: mqtt
    topic: zigbee2mqtt/+/action

# ========================================
# VARIABLES
# ========================================
variables:
  smooth_light: !input smooth_dimming_entity
  smooth_step: !input smooth_step_size
  
  # Get the action from the event
  action: >
    {% if trigger.event.data.type is defined %}
      {{ trigger.event.data.type }}
    {% elif trigger.event.data.command is defined %}
      {{ trigger.event.data.command }}
    {% elif trigger.payload_json.action is defined %}
      {{ trigger.payload_json.action }}
    {% elif trigger.payload is defined %}
      {{ trigger.payload }}
    {% else %}
      unknown
    {% endif %}
  
  # Get parameters like step count or rotation amount
  param: >
    {% if trigger.event.data.value is defined %}
      {{ trigger.event.data.value | int(0) }}
    {% elif trigger.event.data.params is defined and trigger.event.data.params.step_count is defined %}
      {{ trigger.event.data.params.step_count | int(0) }}
    {% else %}
      1
    {% endif %}

# ========================================
# ACTIONS
# ========================================
mode: restart
max_exceeded: silent

action:
  - choose:
      # Button: Single Press
      - conditions: >
          {{ action in ['Press', 'single_press', 'press', 'InitialPress'] }}
        sequence: !input single_press_action
      
      # Button: Double Press
      - conditions: >
          {{ action in ['MultiPressComplete', 'double_press', 'multi_press_2'] and param == 2 }}
        sequence: !input double_press_action
      
      # Button: Long Press
      - conditions: >
          {{ action in ['LongPress', 'long_press', 'hold', 'LongRelease'] }}
        sequence: !input long_press_action
      
      # Scroll: Up/Right
      - conditions: >
          {{ action in ['SwitchLatched', 'rotate_right', 'scroll_up'] and param > 0 }}
        sequence: !input scroll_up_action
      
      # Scroll: Down/Left  
      - conditions: >
          {{ action in ['SwitchLatched', 'rotate_left', 'scroll_down'] and param < 0 }}
        sequence: !input scroll_down_action
      
      # Smooth Dimming (if light is configured)
      - conditions: >
          {{ smooth_light != '' and action == 'SwitchLatched' }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ smooth_light }}"
            data:
              brightness_step_pct: "{{ param * smooth_step }}"
    
    default: []