blueprint:
  name: IKEA BILRESA Scroll Wheel Remote Controller
  description: |
    Professional automation blueprint for the IKEA BILRESA Matter remote.
    
    Controls up to 3 groups:
    - Group 1 (Buttons 1/3/5): Lights - Toggle on single press, dim/brighten on scroll (multi-press).
    - Group 2 (Buttons 2/4): Media - Play/pause on single, volume up/down on scroll.
    - Group 3 (Buttons 6/7/8/9): Covers - Open/close on single, position adjust on scroll.
    
    Requires Matter integration. Scroll notches = press_count (1-18) for stepped control.
  domain: automation
  input:
    remote_device:
      name: BILRESA Remote Device
      description: Select the Matter BILRESA device (IKEA of Sweden).
      selector:
        device:
          integration: matter
          manufacturer: "IKEA of Sweden"
          model: "BILRESA scroll wheel"
    light_entity:
      name: Light Entity (Group 1)
      description: Light(s) for toggle/dimming (e.g., light.living_room).
      default: {}
      selector:
        entity:
          domain: light
    media_entity:
      name: Media Player (Group 2)
      description: Speaker for volume/playback (e.g., media_player.tv).
      default: {}
      selector:
        entity:
          domain: media_player
    cover_entity:
      name: Cover Entity (Group 3)
      description: Blinds/shades for position control (e.g., cover.kitchen_blinds).
      default: {}
      selector:
        entity:
          domain: cover
    brightness_step:
      name: Brightness/Volume Step %
      description: Adjustment per scroll notch (default: 5%).
      default: 5
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"
    position_step:
      name: Cover Position Step %
      description: Adjustment per scroll notch for blinds (default: 10%).
      default: 10
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: "%"

variables:
  press_number: "{{ trigger.event.data.button_number }}"
  press_count: "{{ trigger.event.data.press_count | int(1) }}"
  step_pct: !input brightness_step
  pos_step: !input position_step
  light_ent: !input light_entity
  media_ent: !input media_entity
  cover_ent: !input cover_entity

trigger:
  - platform: event
    event_type: matter_button_press
    event_data:
      device_id: !input remote_device

condition: []

action:
  - choose:
      # Group 1: Lights (Buttons 1,3,5)
      - conditions:
          - condition: template
            value_template: "{{ press_number in [1, 3, 5] }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ press_count == 1 }}"
            then:
              - if:
                  - condition: template
                    value_template: "{{ press_number == 1 }}"
                then:
                  - service: light.toggle
                    target:
                      entity_id: "{{ light_ent }}"
                else:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_ent }}"
                    data:
                      brightness_step_pct: "{{ step_pct * press_count if press_number == 3 else -step_pct * press_count }}"
      # Group 2: Media (Buttons 2,4)
      - conditions:
          - condition: template
            value_template: "{{ press_number in [2, 4] }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ press_count == 1 }}"
            then:
              - service: media_player.media_play_pause
                target:
                  entity_id: "{{ media_ent }}"
            else:
              - service: media_player.volume_set
                target:
                  entity_id: "{{ media_ent }}"
                data:
                  volume_level: >-
                    {% set current_vol = state_attr(media_ent, 'volume_level') | float(0.5) %}
                    {% set delta = step_pct / 100 * press_count %}
                    {% set new_vol = [0.0, 1.0] | max([0.0, 1.0] | min(current_vol + (delta if press_number == 2 else -delta))) %}
                    {{ new_vol }}
      # Group 3: Covers (Buttons 6,7,8,9)
      - conditions:
          - condition: template
            value_template: "{{ press_number in [6, 7, 8, 9] }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ press_count == 1 }}"
            then:
              - if:
                  - condition: template
                    value_template: "{{ press_number in [6, 8] }}"
                then:
                  - service: cover.open_cover
                    target:
                      entity_id: "{{ cover_ent }}"
                else:
                  - service: cover.close_cover
                    target:
                      entity_id: "{{ cover_ent }}"
            else:
              - service: cover.set_cover_position
                target:
                  entity_id: "{{ cover_ent }}"
                data:
                  position: >-
                    {% set current_pos = state_attr(cover_ent, 'current_position') | int(50) %}
                    {% set delta = pos_step * press_count %}
                    {% set new_pos = [0, 100] | max([0, 100] | min(current_pos + (delta if press_number in [6,7] else -delta))) %}
                    {{ new_pos }}
    default: []  # Ignore unassigned buttons
  mode: queued
  max: 10  # Queue fast scrolls
  max_exceeded: silent