blueprint:
  name: IKEA Bilresa - Simple Light Control
  description: |
    Enkel styrning av ljus med IKEA Bilresa Matter remote.
    Button (1) = Tänd/Släck
    Button (3) = Höj ljusstyrka  
    Button (4) = Sänk ljusstyrka
  domain: automation
  input:
    bilresa_device:
      name: Bilresa Remote
      description: Välj din Bilresa fjärrkontroll
      selector:
        device:
          manufacturer: IKEA of Sweden
          model: BILRESA scroll wheel
    
    target_light:
      name: Ljus att styra
      description: Vilket ljus ska remoten styra?
      selector:
        entity:
          domain: light

trigger:
  - platform: device
    device_id: !input bilresa_device
    domain: matter
    type: action
    subtype: button_1
    id: button_1
  
  - platform: device
    device_id: !input bilresa_device
    domain: matter
    type: action
    subtype: button_3
    id: button_3
  
  - platform: device
    device_id: !input bilresa_device
    domain: matter
    type: action
    subtype: button_4
    id: button_4

action:
  - choose:
      # Button 1: Toggle light
      - conditions:
          - condition: trigger
            id: button_1
        sequence:
          - service: light.toggle
            target:
              entity_id: !input target_light
      
      # Button 3: Brightness up
      - conditions:
          - condition: trigger
            id: button_3
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: 10
      
      # Button 4: Brightness down
      - conditions:
          - condition: trigger
            id: button_4
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: -10

mode: restart
