blueprint:
  name: IKEA Bilresa Scroll Wheel Remote (Enhanced)
  description: >
    Fully enhanced blueprint for the IKEA Bilresa scroll‑wheel remote (fjarr_med_skroll).
    Includes:
      ✓ Dynamic scroll notch count (multi_press_N)
      ✓ Group-based control (3 groups)
      ✓ Matter, ZHA, and Zigbee2MQTT support
      ✓ Smooth dimming engine
      ✓ Button/scroll automation mapping
    Works with Matter (matter_event), ZHA (zha_event), and Zigbee2MQTT (mqtt payloads).
  domain: automation
  input:
    remote_device:
      name: Bilresa Remote Device
      description: Select your Bilresa scroll wheel remote.
      selector:
        device: {}
    single_press_action:
      name: Single Press
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press
      default: []
      selector:
        action: {}
    long_press_action:
      name: Long Press
      default: []
      selector:
        action: {}
    scroll_up_action:
      name: Scroll Up (simple)
      default: []
      selector:
        action: {}
    scroll_down_action:
      name: Scroll Down (simple)
      default: []
      selector:
        action: {}
    smooth_dimming_entity:
      name: Light for Smooth Dimming
      description: Light that smooth‑scroll dimming should control.
      default: ''
      selector:
        entity:
          domain: light
    smooth_step_size:
      name: Smooth Dimming Step Size (%)
      default: 4
      selector:
        number:
          min: 1
          max: 20
          mode: slider
    group1_action:
      name: Group 1 Scroll Action
      default: []
      selector:
        action: {}
    group2_action:
      name: Group 2 Scroll Action
      default: []
      selector:
        action: {}
    group3_action:
      name: Group 3 Scroll Action
      default: []
      selector:
        action: {}

# ----------------------------
# Triggers
# ----------------------------
# We listen for Matter, ZHA, and Zigbee2MQTT events.
# Blueprint will automatically process whichever event source fires.
# ----------------------------
trigger:
  # Matter events
  - platform: event
    event_type: matter_event
    id: matter_raw

  # ZHA events
  - platform: event
    event_type: zha_event
    id: zha_raw

  # Zigbee2MQTT (MQTT message with action)
  - platform: mqtt
    topic: zigbee2mqtt/*/action
    id: z2m_raw

# ----------------------------
# Variables
# ----------------------------
variables:
  remote_id: !input remote_device
  smooth_light: !input smooth_dimming_entity
  smooth_step: !input smooth_step_size

  event_payload: "{{ trigger }}"

  # Normalize action names from any integration
  normalized_action: >
    {% if trigger.platform == 'event' and trigger.event.data.action is defined %}
      {{ trigger.event.data.action }}
    {% elif trigger.platform == 'mqtt' %}
      {{ trigger.payload }}
    {% else %}
      unknown
    {% endif %}

  notch_count: >
    {% if 'multi_press_' in normalized_action %}
      {{ normalized_action.split('multi_press_')[1] | int }}
    {% else %}
      1
    {% endif %}

  # Group selection placeholder (Matter/ZHA variants differ)
  selected_group: >
    {% if trigger.platform == 'event' and trigger.event.data.group is defined %}
      {{ trigger.event.data.group }}
    {% else %}
      none
    {% endif %}

# ----------------------------
# Actions
# ----------------------------
mode: restart
max_exceeded: silent

action:
  - choose:

      # ----------------------------
      # BASIC BUTTON ACTIONS
      # ----------------------------
      - conditions: "{{ normalized_action == 'single_press' }}"
        sequence: !input single_press_action

      - conditions: "{{ normalized_action == 'double_press' }}"
        sequence: !input double_press_action

      - conditions: "{{ normalized_action == 'long_press' }}"
        sequence: !input long_press_action

      # ----------------------------
      # SIMPLE SCROLL UP / DOWN
      # ----------------------------
      - conditions: "{{ normalized_action in ['multi_press_1','scroll_up','rotate_right'] }}"
        sequence: !input scroll_up_action

      - conditions: "{{ normalized_action in ['multi_press_2','scroll_down','rotate_left'] }}"
        sequence: !input scroll_down_action

      # ----------------------------
      # SMOOTH DIMMING MODE (multi_press_N)
      # ----------------------------
      - conditions: "{{ 'multi_press_' in normalized_action }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ smooth_light }}"
            data:
              brightness_step_pct: "{{ notch_count * smooth_step }}"

      # ----------------------------
      # GROUP‑BASED SCROLLING
      # ----------------------------
      - conditions: "{{ selected_group == '1' }}"
        sequence: !input group1_action

      - conditions: "{{ selected_group == '2' }}"
        sequence: !input group2_action

      - conditions: "{{ selected_group == '3' }}"
        sequence: !input group3_action

    default: []