blueprint:
  name: IKEA Bilresa Scroll Wheel Remote
  description: |
    Control multiple lights with modes using the IKEA Bilresa scroll wheel remote.
    - Single press: Toggle light on/off
    - Double press: Switch between brightness and temperature modes
    - Long press: Switch to next group/light
    - Scroll wheel: Adjust brightness or temperature based on current mode
  domain: automation
  input:
    # ========================================
    # DEVICE SELECTION
    # ========================================
    remote_device:
      name: ðŸŽ›ï¸ Remote Device
      description: Select your Bilresa scroll wheel remote
      selector:
        device: {}
    
    # ========================================
    # GROUP 1 - LIGHT CONTROL
    # ========================================
    group1_light:
      name: "ðŸ’¡ Group 1 - Light"
      description: "First light to control"
      default: ""
      selector:
        entity:
          domain: light
    
    group1_mode_helper:
      name: "ðŸ”„ Group 1 - Mode Helper"
      description: "Input boolean to track mode (brightness vs temperature). Create one via Settings > Devices > Helpers"
      default: ""
      selector:
        entity:
          domain: input_boolean
    
    # ========================================
    # GROUP 2 - LIGHT CONTROL
    # ========================================
    group2_light:
      name: "ðŸ’¡ Group 2 - Light"
      description: "Second light to control"
      default: ""
      selector:
        entity:
          domain: light
    
    group2_mode_helper:
      name: "ðŸ”„ Group 2 - Mode Helper"
      description: "Input boolean to track mode (brightness vs temperature)"
      default: ""
      selector:
        entity:
          domain: input_boolean
    
    # ========================================
    # GROUP 3 - LIGHT CONTROL
    # ========================================
    group3_light:
      name: "ðŸ’¡ Group 3 - Light"
      description: "Third light to control"
      default: ""
      selector:
        entity:
          domain: light
    
    group3_mode_helper:
      name: "ðŸ”„ Group 3 - Mode Helper"
      description: "Input boolean to track mode (brightness vs temperature)"
      default: ""
      selector:
        entity:
          domain: input_boolean
    
    # ========================================
    # SETTINGS
    # ========================================
    active_group_helper:
      name: "ðŸŽ¯ Active Group Helper"
      description: "Input select to track which group (1, 2, or 3) is active. Create with options: '1', '2', '3'"
      selector:
        entity:
          domain: input_select
    
    brightness_step:
      name: "ðŸ“Š Brightness Step"
      description: "How much to change brightness per scroll notch"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          step: 1
          unit_of_measurement: "%"
          mode: slider
    
    temperature_step:
      name: "ðŸŒ¡ï¸ Temperature Step"
      description: "How much to change color temperature per scroll notch (mireds)"
      default: 20
      selector:
        number:
          min: 5
          max: 100
          step: 5
          unit_of_measurement: "mireds"
          mode: slider

# ========================================
# TRIGGERS
# ========================================
trigger:
  - platform: event
    event_type: matter_event
    event_data:
      device_id: !input remote_device
  
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device

# ========================================
# CONDITIONS - Ensure we have required helpers
# ========================================
condition:
  - condition: template
    value_template: "{{ active_group not in ['', 'none', none, 'unknown', 'unavailable'] }}"

# ========================================
# VARIABLES
# ========================================
variables:
  active_group: !input active_group_helper
  brightness_step_size: !input brightness_step
  temp_step_size: !input temperature_step
  
  group1_light: !input group1_light
  group2_light: !input group2_light
  group3_light: !input group3_light
  
  group1_mode: !input group1_mode_helper
  group2_mode: !input group2_mode_helper
  group3_mode: !input group3_mode_helper
  
  # Get current group (1, 2, or 3)
  current_group: "{{ states(active_group) }}"
  
  # Get light for current group
  current_light: >
    {% if states(active_group) == '1' %}
      {{ group1_light }}
    {% elif states(active_group) == '2' %}
      {{ group2_light }}
    {% elif states(active_group) == '3' %}
      {{ group3_light }}
    {% else %}
      none
    {% endif %}
  
  # Get mode helper for current group
  current_mode_helper: >
    {% if states(active_group) == '1' %}
      {{ group1_mode }}
    {% elif states(active_group) == '2' %}
      {{ group2_mode }}
    {% elif states(active_group) == '3' %}
      {{ group3_mode }}
    {% else %}
      none
    {% endif %}
  
  # Check if we're in temperature mode (on) or brightness mode (off)
  is_temperature_mode: "{{ is_state(current_mode_helper, 'on') }}"
  
  # Get the event type - Matter uses 'type' field
  event_type: >
    {% if trigger.event.data.type is defined %}
      {{ trigger.event.data.type }}
    {% else %}
      unknown
    {% endif %}
  
  # Get scroll direction/amount - Matter uses new_position in params
  scroll_value: >
    {% if trigger.event.data.params is defined and trigger.event.data.params.new_position is defined %}
      {{ trigger.event.data.params.new_position | int(0) }}
    {% else %}
      0
    {% endif %}

# ========================================
# ACTIONS
# ========================================
mode: restart
max_exceeded: silent

action:
  - choose:
      # ===== SINGLE PRESS: Toggle current light on/off =====
      - conditions:
          - condition: template
            value_template: "{{ event_type == 'InitialPress' }}"
          - condition: template
            value_template: "{{ current_light not in ['', 'none', none] }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"
      
      # ===== DOUBLE PRESS: Toggle between brightness and temperature modes =====
      - conditions:
          - condition: template
            value_template: "{{ event_type == 'MultiPressComplete' }}"
          - condition: template
            value_template: "{{ current_mode_helper not in ['', 'none', none] }}"
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: "{{ current_mode_helper }}"
      
      # ===== LONG PRESS: Switch to next group =====
      - conditions:
          - condition: template
            value_template: "{{ event_type == 'LongPress' }}"
        sequence:
          - service: input_select.select_next
            target:
              entity_id: "{{ active_group }}"
            data:
              cycle: true
      
      # ===== SCROLL WHEEL: Adjust brightness or temperature =====
      - conditions:
          - condition: template
            value_template: "{{ event_type == 'SwitchLatched' }}"
          - condition: template
            value_template: "{{ scroll_value != 0 }}"
          - condition: template
            value_template: "{{ current_light not in ['', 'none', none] }}"
        sequence:
          - choose:
              # Temperature mode - adjust color temperature
              - conditions:
                  - condition: template
                    value_template: "{{ is_temperature_mode }}"
                  - condition: template
                    value_template: "{{ state_attr(current_light, 'color_temp') != none }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ current_light }}"
                    data:
                      color_temp: >
                        {% set current_temp = state_attr(current_light, 'color_temp') | int(250) %}
                        {% set new_temp = current_temp + (temp_step_size * scroll_value) %}
                        {% set min_temp = state_attr(current_light, 'min_mireds') | int(153) %}
                        {% set max_temp = state_attr(current_light, 'max_mireds') | int(500) %}
                        {{ [min_temp, [max_temp, new_temp] | min] | max }}
            # Brightness mode (default) - adjust brightness
            default:
              - service: light.turn_on
                target:
                  entity_id: "{{ current_light }}"
                data:
                  brightness_step_pct: "{{ brightness_step_size * scroll_value }}"
    
    default: []