blueprint:
  name: IKEA Bilresa (Fjärr med skroll) - Smart Light Control
  description: |
    Control your lights with the IKEA Bilresa/Fjärr med skroll remote via Matter.
    
    **Features:**
    - 3 independent groups (9 buttons total)
    - Left/Right buttons: dim up/down
    - Middle button: toggle on/off
    - Middle button long press: cycle color temperature (warm → neutral → cool)
    
    **Button Layout:**
    - Buttons 1-3: Group 1
    - Buttons 4-6: Group 2  
    - Buttons 7-9: Group 3
    
  domain: automation
  
  input:
    remote_button_1:
      name: Remote Button 1 Event
      description: Select the button 1 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    remote_button_2:
      name: Remote Button 2 Event
      description: Select the button 2 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    remote_button_3:
      name: Remote Button 3 Event
      description: Select the button 3 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    remote_button_4:
      name: Remote Button 4 Event
      description: Select the button 4 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    remote_button_5:
      name: Remote Button 5 Event
      description: Select the button 5 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    remote_button_6:
      name: Remote Button 6 Event
      description: Select the button 6 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    remote_button_7:
      name: Remote Button 7 Event
      description: Select the button 7 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    remote_button_8:
      name: Remote Button 8 Event
      description: Select the button 8 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    remote_button_9:
      name: Remote Button 9 Event
      description: Select the button 9 event entity
      selector:
        entity:
          filter:
            - domain: event
    
    group1_light:
      name: Group 1 Light (Buttons 1-3)
      description: Light(s) controlled by buttons 1-3
      selector:
        entity:
          filter:
            - domain: light
    
    group2_light:
      name: Group 2 Light (Buttons 4-6)
      description: Light(s) controlled by buttons 4-6
      selector:
        entity:
          filter:
            - domain: light
    
    group3_light:
      name: Group 3 Light (Buttons 7-9)
      description: Light(s) controlled by buttons 7-9
      selector:
        entity:
          filter:
            - domain: light
    
    brightness_step:
      name: Brightness Step
      description: Percentage to increase/decrease brightness per button press
      default: 10
      selector:
        number:
          min: 5
          max: 25
          step: 5
          unit_of_measurement: "%"
    
    transition_time:
      name: Transition Time
      description: Smooth transition duration for brightness changes
      default: 1
      selector:
        number:
          min: 0
          max: 5
          step: 1
          unit_of_measurement: "s"
    
    temp_warm:
      name: Warm Color Temperature
      description: Warm white color temperature in Kelvin
      default: 2700
      selector:
        number:
          min: 2000
          max: 3500
          step: 100
          unit_of_measurement: "K"
    
    temp_neutral:
      name: Neutral Color Temperature
      description: Neutral white color temperature in Kelvin
      default: 4000
      selector:
        number:
          min: 3500
          max: 5000
          step: 100
          unit_of_measurement: "K"
    
    temp_cool:
      name: Cool Color Temperature
      description: Cool white color temperature in Kelvin
      default: 6000
      selector:
        number:
          min: 5000
          max: 7000
          step: 100
          unit_of_measurement: "K"

mode: restart
max_exceeded: silent

triggers:
  - entity_id: !input remote_button_1
    id: btn1
    trigger: state
  - entity_id: !input remote_button_2
    id: btn2
    trigger: state
  - entity_id: !input remote_button_3
    id: btn3
    trigger: state
  - entity_id: !input remote_button_4
    id: btn4
    trigger: state
  - entity_id: !input remote_button_5
    id: btn5
    trigger: state
  - entity_id: !input remote_button_6
    id: btn6
    trigger: state
  - entity_id: !input remote_button_7
    id: btn7
    trigger: state
  - entity_id: !input remote_button_8
    id: btn8
    trigger: state
  - entity_id: !input remote_button_9
    id: btn9
    trigger: state

actions:
  - variables:
      target_light: >
        {% if trigger.id in ['btn1', 'btn2', 'btn3'] %}
          !input group1_light
        {% elif trigger.id in ['btn4', 'btn5', 'btn6'] %}
          !input group2_light
        {% else %}
          !input group3_light
        {% endif %}
      is_long: "{{ trigger.to_state.attributes.event_type == 'long_press' }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_long and trigger.id in ['btn3', 'btn6', 'btn9'] }}"
        sequence:
          - target:
              entity_id: "{{ target_light }}"
            data:
              color_temp_kelvin: >
                {% set current = state_attr(target_light, 'color_temp_kelvin') | int(!input temp_warm) %}
                {% if current < !input temp_neutral %}
                  !input temp_neutral
                {% elif current < !input temp_cool %}
                  !input temp_cool
                {% else %}
                  !input temp_warm
                {% endif %}
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn3', 'btn6', 'btn9'] and not is_long }}"
        sequence:
          - target:
              entity_id: "{{ target_light }}"
            action: light.toggle
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn1', 'btn4', 'btn7'] }}"
        sequence:
          - target:
              entity_id: "{{ target_light }}"
            data:
              brightness_step_pct: !input brightness_step
              transition: !input transition_time
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn2', 'btn5', 'btn8'] }}"
        sequence:
          - target:
              entity_id: "{{ target_light }}"
            data:
              brightness_step_pct: "{{ 0 - (!input brightness_step) }}"
              transition: !input transition_time
            action: light.turn_on