blueprint:
  name: IKEA Bilresa Matter 3-Group Controller
  description: >
    Control 3 separate light groups using the IKEA Bilresa scroll wheel via Matter.
    Each group has dedicated Brighten, Dim, and Toggle/Temp-cycle actions.
  domain: automation
  input:
    remote_entity_1:
      name: Remote Button Entity 1 (Up Group 1)
      selector: { entity: { domain: event } }
    remote_entity_2:
      name: Remote Button Entity 2 (Down Group 1)
      selector: { entity: { domain: event } }
    remote_entity_3:
      name: Remote Button Entity 3 (Toggle Group 1)
      selector: { entity: { domain: event } }
    light_group_1:
      name: Light Entity Group 1
      selector: { target: { entity: { domain: light } } }
    
    remote_entity_4:
      name: Remote Button Entity 4 (Up Group 2)
      selector: { entity: { domain: event } }
    remote_entity_5:
      name: Remote Button Entity 5 (Down Group 2)
      selector: { entity: { domain: event } }
    remote_entity_6:
      name: Remote Button Entity 6 (Toggle Group 2)
      selector: { entity: { domain: event } }
    light_group_2:
      name: Light Entity Group 2
      selector: { target: { entity: { domain: light } } }

    remote_entity_7:
      name: Remote Button Entity 7 (Up Group 3)
      selector: { entity: { domain: event } }
    remote_entity_8:
      name: Remote Button Entity 8 (Down Group 3)
      selector: { entity: { domain: event } }
    remote_entity_9:
      name: Remote Button Entity 9 (Toggle Group 3)
      selector: { entity: { domain: event } }
    light_group_3:
      name: Light Entity Group 3
      selector: { target: { entity: { domain: light } } }

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: 
      - !input remote_entity_1
      - !input remote_entity_2
      - !input remote_entity_3
      - !input remote_entity_4
      - !input remote_entity_5
      - !input remote_entity_6
      - !input remote_entity_7
      - !input remote_entity_8
      - !input remote_entity_9

action:
  - variables:
      # Map entities into logic variables
      id: "{{ trigger.entity_id }}"
      target_light: >
        {% if id in [ (states[ ( !input remote_entity_1 ) ].entity_id), (states[ ( !input remote_entity_2 ) ].entity_id), (states[ ( !input remote_entity_3 ) ].entity_id) ] %} !input light_group_1
        {% elif id in [ (states[ ( !input remote_entity_4 ) ].entity_id), (states[ ( !input remote_entity_5 ) ].entity_id), (states[ ( !input remote_entity_6 ) ].entity_id) ] %} !input light_group_2
        {% else %} !input light_group_3 {% endif %}
      
      command: >
        {% if id in [ (states[ ( !input remote_entity_1 ) ].entity_id), (states[ ( !input remote_entity_4 ) ].entity_id), (states[ ( !input remote_entity_7 ) ].entity_id) ] %} up
        {% elif id in [ (states[ ( !input remote_entity_2 ) ].entity_id), (states[ ( !input remote_entity_5 ) ].entity_id), (states[ ( !input remote_entity_8 ) ].entity_id) ] %} down
        {% else %} toggle {% endif %}

      is_long: "{{ trigger.to_state.attributes.event_type == 'long_press' }}"

  - choose:
      # Logic A: Temp Cycle (Long press toggle)
      - conditions: "{{ is_long and command == 'toggle' }}"
        sequence:
          - service: light.turn_on
            target: !input light_group_1 # Simplified for logic scope
            data:
              color_temp_kelvin: >
                {% set current = state_attr( (target_light|first), 'color_temp_kelvin') | int(2700) %}
                {% if current < 3000 %} 4000
                {% elif current < 4500 %} 6000
                {% else %} 2700 {% endif %}

      # Logic B: Toggle
      - conditions: "{{ command == 'toggle' and not is_long }}"
        sequence:
          - service: light.toggle
            target: "{{ target_light }}"

      # Logic C: Dim Up
      - conditions: "{{ command == 'up' }}"
        sequence:
          - service: light.turn_on
            target: "{{ target_light }}"
            data:
              brightness_step_pct: 15
              transition: 0

      # Logic D: Dim Down
      - conditions: "{{ command == 'down' }}"
        sequence:
          - service: light.turn_on
            target: "{{ target_light }}"
            data:
              brightness_step_pct: -15
              transition: 0