blueprint:
  name: IKEA BILRESA Matter Scroll Wheel (Fixed)
  description: >
    Control actions with an IKEA BILRESA Matter Scroll Wheel.
    
    **Features:**
    - **Click:** Supports Single Click (via Matter GenericSwitch Cluster 59).
    - **Scroll:** Supports Rotate Left/Right (via Matter LevelControl Cluster 8).
    - **Multi-Group:** Optional 'Modes' using a dropdown helper.
    
    **Troubleshooting:**
    If actions don't trigger, ensure you selected the correct "Matter Device" 
    and that the device has not fallen into deep sleep (press the button once to wake it).
  domain: automation
  input:
    matter_device_id:
      name: Matter Device
      description: Select the IKEA BILRESA device.
      selector:
        device:
          integration: matter
          multiple: false

    group_helper:
      name: Group Helper (Optional)
      description: "An Input Select entity to track modes. (Leave empty for single mode)."
      default: {}
      selector:
        entity:
          domain: input_select
          multiple: false

    # --- GROUP 1 ---
    g1_label:
      name: "--- GROUP 1 SETTINGS ---"
      description: "Active if Helper is empty or 'Group 1'."
      default: {}
      selector:
        label: {}

    action_click_g1:
      name: Single Click (Group 1)
      default: []
      selector:
        action: {}

    action_scroll_up_g1:
      name: Scroll Up / Right (Group 1)
      description: "Clockwise rotation."
      default: []
      selector:
        action: {}

    action_scroll_down_g1:
      name: Scroll Down / Left (Group 1)
      description: "Counter-clockwise rotation."
      default: []
      selector:
        action: {}

    # --- GROUP 2 ---
    g2_label:
      name: "--- GROUP 2 SETTINGS ---"
      description: "Active if Helper is 'Group 2'."
      default: {}
      selector:
        label: {}

    action_click_g2:
      name: Single Click (Group 2)
      default: []
      selector:
        action: {}

    action_scroll_up_g2:
      name: Scroll Up / Right (Group 2)
      default: []
      selector:
        action: {}

    action_scroll_down_g2:
      name: Scroll Down / Left (Group 2)
      default: []
      selector:
        action: {}

mode: queued
max: 10

trigger:
  - platform: event
    event_type: matter_event
    event_data:
      device_id: !input matter_device_id 

variables:
  # Inputs
  helper_entity: !input group_helper
  
  # Event Parsing
  cluster_id: "{{ trigger.event.data.cluster_id }}"
  command_id: "{{ trigger.event.data.command_id }}"
  args: "{{ trigger.event.data.args }}"
  
  # Group Logic
  current_group: >
    {% if helper_entity == {} %}
      Group 1
    {% else %}
      {{ states(helper_entity) }}
    {% endif %}

  # --- LOGIC ---
  # Click: Cluster 59 (GenericSwitch). Command 6 (MultiPressComplete) or 2 (ShortRelease)
  # Arg: totalNumberOfPressesCounted = 1
  is_click: >
    {{ 
      cluster_id == 59 and 
      (command_id == 6 or command_id == 2) and
      (args.totalNumberOfPressesCounted | default(1) == 1)
    }}

  # Scroll Up: Cluster 8 (LevelControl). Command 2 (Step). stepMode = 0 (Up).
  is_scroll_up: >
    {{ 
      cluster_id == 8 and 
      command_id == 2 and 
      (args.stepMode | default(99) == 0) 
    }}

  # Scroll Down: Cluster 8 (LevelControl). Command 2 (Step). stepMode = 1 (Down).
  is_scroll_down: >
    {{ 
      cluster_id == 8 and 
      command_id == 2 and 
      (args.stepMode | default(99) == 1) 
    }}

action:
  - choose:
      # GROUP 1
      - conditions: "{{ current_group == 'Group 1' }}"
        sequence:
          - choose:
              - conditions: "{{ is_click }}"
                sequence: !input action_click_g1
              - conditions: "{{ is_scroll_up }}"
                sequence: !input action_scroll_up_g1
              - conditions: "{{ is_scroll_down }}"
                sequence: !input action_scroll_down_g1
                
      # GROUP 2
      - conditions: "{{ current_group == 'Group 2' }}"
        sequence:
          - choose:
              - conditions: "{{ is_click }}"
                sequence: !input action_click_g2
              - conditions: "{{ is_scroll_up }}"
                sequence: !input action_scroll_up_g2
              - conditions: "{{ is_scroll_down }}"
                sequence: !input action_scroll_down_g2