blueprint:
  name: IKEA Bilresa (Fjärr med skroll) - Smart Light Control
  description: |
    Control your lights with the IKEA Bilresa/Fjärr med skroll remote via Matter.
    
    **Features:**
    - 3 independent groups (9 buttons total)
    - Left/Right buttons: dim up/down (±10%)
    - Middle button: toggle on/off
    - Middle button long press: cycle color temperature (warm → neutral → cool)
    
    **Button Layout:**
    - Buttons 1-3: Group 1
    - Buttons 4-6: Group 2  
    - Buttons 7-9: Group 3
    
  domain: automation
  
  input:
    remote_button_1:
      name: Remote Button 1 Event
      description: Select the button 1 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    remote_button_2:
      name: Remote Button 2 Event
      description: Select the button 2 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    remote_button_3:
      name: Remote Button 3 Event
      description: Select the button 3 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    remote_button_4:
      name: Remote Button 4 Event
      description: Select the button 4 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    remote_button_5:
      name: Remote Button 5 Event
      description: Select the button 5 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    remote_button_6:
      name: Remote Button 6 Event
      description: Select the button 6 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    remote_button_7:
      name: Remote Button 7 Event
      description: Select the button 7 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    remote_button_8:
      name: Remote Button 8 Event
      description: Select the button 8 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    remote_button_9:
      name: Remote Button 9 Event
      description: Select the button 9 event entity from your remote
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
    
    group1_light:
      name: Group 1 Light (Buttons 1-3)
      description: Light(s) controlled by buttons 1-3
      selector:
        entity:
          filter:
            - domain: light
          multiple: false
    
    group2_light:
      name: Group 2 Light (Buttons 4-6)
      description: Light(s) controlled by buttons 4-6
      selector:
        entity:
          filter:
            - domain: light
          multiple: false
    
    group3_light:
      name: Group 3 Light (Buttons 7-9)
      description: Light(s) controlled by buttons 7-9
      selector:
        entity:
          filter:
            - domain: light
          multiple: false
    
    brightness_step:
      name: Brightness Step
      description: Percentage to increase/decrease brightness per button press
      default: 10
      selector:
        number:
          min: 5
          max: 25
          step: 5
          unit_of_measurement: "%"
    
    transition_time:
      name: Transition Time
      description: Smooth transition duration for brightness changes
      default: 1.0
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.5
          unit_of_measurement: "s"
    
    enable_color_temp_cycle:
      name: Enable Color Temperature Cycling
      description: Enable long press on middle buttons to cycle through color temperatures
      default: true
      selector:
        boolean:
    
    temp_warm:
      name: Warm Color Temperature
      description: Warm white color temperature in Kelvin
      default: 2700
      selector:
        number:
          min: 2000
          max: 3500
          step: 100
          unit_of_measurement: "K"
    
    temp_neutral:
      name: Neutral Color Temperature
      description: Neutral white color temperature in Kelvin
      default: 4000
      selector:
        number:
          min: 3500
          max: 5000
          step: 100
          unit_of_measurement: "K"
    
    temp_cool:
      name: Cool Color Temperature
      description: Cool white color temperature in Kelvin
      default: 6000
      selector:
        number:
          min: 5000
          max: 7000
          step: 100
          unit_of_measurement: "K"

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input remote_button_1
    id: btn1
  - trigger: state
    entity_id: !input remote_button_2
    id: btn2
  - trigger: state
    entity_id: !input remote_button_3
    id: btn3
  - trigger: state
    entity_id: !input remote_button_4
    id: btn4
  - trigger: state
    entity_id: !input remote_button_5
    id: btn5
  - trigger: state
    entity_id: !input remote_button_6
    id: btn6
  - trigger: state
    entity_id: !input remote_button_7
    id: btn7
  - trigger: state
    entity_id: !input remote_button_8
    id: btn8
  - trigger: state
    entity_id: !input remote_button_9
    id: btn9

actions:
  - variables:
      target_light: >
        {% if trigger.id in ['btn1', 'btn2', 'btn3'] %}
          {{ group1_light }}
        {% elif trigger.id in ['btn4', 'btn5', 'btn6'] %}
          {{ group2_light }}
        {% else %}
          {{ group3_light }}
        {% endif %}
      is_long: "{{ trigger.to_state.attributes.event_type == 'long_press' }}"
      warm_temp: !input temp_warm
      neutral_temp: !input temp_neutral
      cool_temp: !input temp_cool
      step_pct: !input brightness_step
      transition_sec: !input transition_time
      color_temp_enabled: !input enable_color_temp_cycle
  
  - choose:
      # Middle button long press - cycle color temperature (if enabled)
      - conditions:
          - condition: template
            value_template: "{{ color_temp_enabled and is_long and trigger.id in ['btn3', 'btn6', 'btn9'] }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              color_temp_kelvin: >
                {% set current = state_attr(target_light, 'color_temp_kelvin') | int(warm_temp) %}
                {% if current < neutral_temp %}
                  {{ neutral_temp }}
                {% elif current < cool_temp %}
                  {{ cool_temp }}
                {% else %}
                  {{ warm_temp }}
                {% endif %}
      
      # Middle button - toggle
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn3', 'btn6', 'btn9'] and not is_long }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: "{{ target_light }}"
      
      # Left button - brightness up
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn1', 'btn4', 'btn7'] }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              brightness_step_pct: "{{ step_pct }}"
              transition: "{{ transition_sec }}"
      
      # Right button - brightness down
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn2', 'btn5', 'btn8'] }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              brightness_step_pct: "{{ -step_pct }}"
              transition: "{{ transition_sec }}"