blueprint:
  name: IKEA Matter Scroll Wheel (Multi-Group)
  description: >
    Control actions with an IKEA Matter Scroll Wheel (or similar Matter rotary devices).
    
    Supports:
    - Center Press (Click)
    - Scroll Up (Rotate Right)
    - Scroll Down (Rotate Left)
    
    **Group Logic:**
    Optionally link an Input Select (Dropdown) helper to enable "Modes". 
    If defined, the blueprint checks the state of the helper to determine which 
    set of actions to run (Group 1, 2, or 3).
    
    **Note:** This blueprint listens for `matter_event`. Ensure your device ID is correct.
  domain: automation
  input:
    matter_device_id:
      name: Matter Device
      description: Select the IKEA Matter device.
      selector:
        device:
          integration: matter
          multiple: false

    group_helper:
      name: Group Helper (Optional)
      description: >
        An Input Select entity to track the current group/mode. 
        If left empty, only "Group 1" actions will ever execute.
      default: {}
      selector:
        entity:
          domain: input_select
          multiple: false

    # ---------------- GROUP 1 INPUTS ----------------
    g1_header:
      name: "--- GROUP 1 SETTINGS ---"
      description: "Default actions. (Active if Helper is empty or set to Group 1)"
      default: {}
      selector:
        label: {}

    action_press_g1:
      name: Press Action (Group 1)
      description: "Action when wheel is clicked. (Tip: Use this to cycle the Input Select to Group 2!)"
      default: []
      selector:
        action: {}

    action_scroll_up_g1:
      name: Scroll Up / Right (Group 1)
      description: Action when rotated clockwise.
      default: []
      selector:
        action: {}

    action_scroll_down_g1:
      name: Scroll Down / Left (Group 1)
      description: Action when rotated counter-clockwise.
      default: []
      selector:
        action: {}

    # ---------------- GROUP 2 INPUTS ----------------
    g2_header:
      name: "--- GROUP 2 SETTINGS ---"
      description: "Active only if Helper is set to Group 2"
      default: {}
      selector:
        label: {}

    action_press_g2:
      name: Press Action (Group 2)
      default: []
      selector:
        action: {}

    action_scroll_up_g2:
      name: Scroll Up / Right (Group 2)
      default: []
      selector:
        action: {}

    action_scroll_down_g2:
      name: Scroll Down / Left (Group 2)
      default: []
      selector:
        action: {}

    # ---------------- GROUP 3 INPUTS ----------------
    g3_header:
      name: "--- GROUP 3 SETTINGS ---"
      description: "Active only if Helper is set to Group 3"
      default: {}
      selector:
        label: {}

    action_press_g3:
      name: Press Action (Group 3)
      default: []
      selector:
        action: {}

    action_scroll_up_g3:
      name: Scroll Up / Right (Group 3)
      default: []
      selector:
        action: {}

    action_scroll_down_g3:
      name: Scroll Down / Left (Group 3)
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: matter_event
    event_data:
      event_source: !input matter_device_id

variables:
  # Inputs
  helper_entity: !input group_helper
  
  # Event Data
  cluster_id: "{{ trigger.event.data.cluster_id }}"
  command_id: "{{ trigger.event.data.command_id }}"
  args: "{{ trigger.event.data.args }}"
  
  # Determine current group state
  current_group: >
    {% if helper_entity == {} %}
      Group 1
    {% else %}
      {{ states(helper_entity) }}
    {% endif %}

  # --- CLUSTER IDENTIFICATION (Standard Matter) ---
  # OnOff Cluster = 6 (0x0006). Command 2 = Toggle.
  is_press: "{{ cluster_id == 6 and command_id == 2 }}"
  
  # LevelControl Cluster = 8 (0x0008). Command 2 = Step.
  # Arg 0 = Up (0) or Down (1)
  is_scroll_up: "{{ cluster_id == 8 and (command_id == 2 or command_id == 5) and args[0] == 0 }}"
  is_scroll_down: "{{ cluster_id == 8 and (command_id == 2 or command_id == 5) and args[0] == 1 }}"

action:
  - choose:
      # ------------------------------------------------------
      # GROUP 1 LOGIC
      # ------------------------------------------------------
      - conditions:
          - "{{ current_group == 'Group 1' }}"
        sequence:
          - choose:
              - conditions: "{{ is_press }}"
                sequence: !input action_press_g1
              - conditions: "{{ is_scroll_up }}"
                sequence: !input action_scroll_up_g1
              - conditions: "{{ is_scroll_down }}"
                sequence: !input action_scroll_down_g1

      # ------------------------------------------------------
      # GROUP 2 LOGIC
      # ------------------------------------------------------
      - conditions:
          - "{{ current_group == 'Group 2' }}"
        sequence:
          - choose:
              - conditions: "{{ is_press }}"
                sequence: !input action_press_g2
              - conditions: "{{ is_scroll_up }}"
                sequence: !input action_scroll_up_g2
              - conditions: "{{ is_scroll_down }}"
                sequence: !input action_scroll_down_g2

      # ------------------------------------------------------
      # GROUP 3 LOGIC
      # ------------------------------------------------------
      - conditions:
          - "{{ current_group == 'Group 3' }}"
        sequence:
          - choose:
              - conditions: "{{ is_press }}"
                sequence: !input action_press_g3
              - conditions: "{{ is_scroll_up }}"
                sequence: !input action_scroll_up_g3
              - conditions: "{{ is_scroll_down }}"
                sequence: !input action_scroll_down_g3