blueprint:
  name: IKEA Bilresa Matter - One-Select Auto Map
  description: >
    Select the remote device and the lights. 
    It will automatically map buttons 1-9 based on the device selection.
  domain: automation
  input:
    bilresa_remote:
      name: IKEA Bilresa Remote Device
      selector:
        device:
          integration: matter
          model: "BILRESA scroll" # Filter to help limit selection
    light_group_1:
      name: Kitchen Group (Buttons 1-3)
      selector: { target: { entity: { domain: light } } }
    light_group_2:
      name: Sofa Group (Buttons 4-6)
      selector: { target: { entity: { domain: light } } }
    light_group_3:
      name: All Lights Group (Buttons 7-9)
      selector: { target: { entity: { domain: light } } }

mode: restart

# Trigger on any button activity from the selected device
trigger:
  - platform: event
    event_type: matter_event
    event_data:
      device_id: !input bilresa_remote

action:
  - variables:
      # Get the button number from the Matter event payload
      # Assuming buttons are labeled button_1, button_2, etc.
      btn_num: "{{ trigger.event.data.endpoint_id | int }}"
      target_light: >
        {% if btn_num in [1, 2, 3] %} !input light_group_1
        {% elif btn_num in [4, 5, 6] %} !input light_group_2
        {% else %} !input light_group_3 {% endif %}
      
      command: >
        {% if btn_num in [1, 4, 7] %} up
        {% elif btn_num in [2, 5, 8] %} down
        {% else %} toggle {% endif %}

      # Matter event type check
      is_long: "{{ trigger.event.data.event_type == 'long_press' }}"

  - choose:
      # Logic A: Temp Cycle
      - conditions: "{{ is_long and command == 'toggle' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              color_temp_kelvin: >
                {% set current = state_attr(target_light, 'color_temp_kelvin') | int(2700) %}
                {% if current < 3000 %} 4000
                {% elif current < 4500 %} 6000
                {% else %} 2700 {% endif %}

      # Logic B: Standard Actions
      - conditions: "{{ not is_long }}"
        sequence:
          - service: >
              {% if command == 'toggle' %} light.toggle
              {% else %} light.turn_on {% endif %}
            target:
              entity_id: "{{ target_light }}"
            data: >
              {% if command == 'up' %} 
                {"brightness_step_pct": 15, "transition": 0}
              {% elif command == 'down' %} 
                {"brightness_step_pct": -15, "transition": 0}
              {% else %} {} {% endif %}