blueprint:
  name: IKEA Bilresa - State Based Control
  description: |
    Enkel styrning av ljus med IKEA Bilresa Matter remote.
    Använder state changes istället för events.
  domain: automation
  input:
    target_light:
      name: 💡 Ljus att styra
      description: Vilket ljus ska remoten styra?
      selector:
        entity:
          domain: light
    
    brightness_step:
      name: 📊 Ljusstyrkesteg
      description: Hur mycket ska ljusstyrkan ändras per klick?
      default: 10
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: "%"

# No trigger needed - we'll use conditions based on service calls
trigger: []

condition: []

action:
  - service: light.toggle
    target:
      entity_id: !input target_light

mode: single
